subscribers:
  - id: qalcosonic
    name: Qalcosonic W1 StatusCodes
    type: device.statusUpdated
    endpoint: http://localhost:8091/api/cloudevents
    source: github.com/diwise/iot-device-mgmt
    eventType: diwise.statusmessage
    tenants:
      - default
      - test
    entities:
      - idPattern: ^urn:ngsi-ld:Device:.+
