version: '3'
services:
  
  timescale:
    image: timescale/timescaledb-ha:pg17-ts2.18
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

volumes:
  pgadmin-data: ~