// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package devicemanagement

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			GetDeviceFunc: func(ctx context.Context, deviceID string) (*Device, error) {
//				panic("mock out the GetDevice method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// GetDeviceFunc mocks the GetDevice method.
	GetDeviceFunc func(ctx context.Context, deviceID string) (*Device, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDevice holds details about calls to the GetDevice method.
		GetDevice []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DeviceID is the deviceID argument value.
			DeviceID string
		}
	}
	lockGetDevice sync.RWMutex
}

// GetDevice calls GetDeviceFunc.
func (mock *ClientMock) GetDevice(ctx context.Context, deviceID string) (*Device, error) {
	if mock.GetDeviceFunc == nil {
		panic("ClientMock.GetDeviceFunc: method is nil but Client.GetDevice was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		DeviceID string
	}{
		Ctx:      ctx,
		DeviceID: deviceID,
	}
	mock.lockGetDevice.Lock()
	mock.calls.GetDevice = append(mock.calls.GetDevice, callInfo)
	mock.lockGetDevice.Unlock()
	return mock.GetDeviceFunc(ctx, deviceID)
}

// GetDeviceCalls gets all the calls that were made to GetDevice.
// Check the length with:
//
//	len(mockedClient.GetDeviceCalls())
func (mock *ClientMock) GetDeviceCalls() []struct {
	Ctx      context.Context
	DeviceID string
} {
	var calls []struct {
		Ctx      context.Context
		DeviceID string
	}
	mock.lockGetDevice.RLock()
	calls = mock.calls.GetDevice
	mock.lockGetDevice.RUnlock()
	return calls
}
