// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mqtt

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			EnabledFunc: func() bool {
//				panic("mock out the Enabled method")
//			},
//			PublishFunc: func(ctx context.Context, msg TopicMessage) error {
//				panic("mock out the Publish method")
//			},
//			StartFunc: func(ctx context.Context)  {
//				panic("mock out the Start method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// EnabledFunc mocks the Enabled method.
	EnabledFunc func() bool

	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, msg TopicMessage) error

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Enabled holds details about calls to the Enabled method.
		Enabled []struct {
		}
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Msg is the msg argument value.
			Msg TopicMessage
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockEnabled sync.RWMutex
	lockPublish sync.RWMutex
	lockStart   sync.RWMutex
}

// Enabled calls EnabledFunc.
func (mock *ClientMock) Enabled() bool {
	if mock.EnabledFunc == nil {
		panic("ClientMock.EnabledFunc: method is nil but Client.Enabled was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEnabled.Lock()
	mock.calls.Enabled = append(mock.calls.Enabled, callInfo)
	mock.lockEnabled.Unlock()
	return mock.EnabledFunc()
}

// EnabledCalls gets all the calls that were made to Enabled.
// Check the length with:
//
//	len(mockedClient.EnabledCalls())
func (mock *ClientMock) EnabledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEnabled.RLock()
	calls = mock.calls.Enabled
	mock.lockEnabled.RUnlock()
	return calls
}

// Publish calls PublishFunc.
func (mock *ClientMock) Publish(ctx context.Context, msg TopicMessage) error {
	if mock.PublishFunc == nil {
		panic("ClientMock.PublishFunc: method is nil but Client.Publish was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Msg TopicMessage
	}{
		Ctx: ctx,
		Msg: msg,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, msg)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedClient.PublishCalls())
func (mock *ClientMock) PublishCalls() []struct {
	Ctx context.Context
	Msg TopicMessage
} {
	var calls []struct {
		Ctx context.Context
		Msg TopicMessage
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *ClientMock) Start(ctx context.Context) {
	if mock.StartFunc == nil {
		panic("ClientMock.StartFunc: method is nil but Client.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedClient.StartCalls())
func (mock *ClientMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
